/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as LayoutaImport } from './routes/_layouta'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout.index'
import { Route as EventIdImport } from './routes/event.$id'
import { Route as LayoutaTasksImport } from './routes/_layouta.tasks'
import { Route as EventIdNotesImport } from './routes/event.$id.notes'
import { Route as EventIdNextStepsImport } from './routes/event.$id.next-steps'
import { Route as EventIdDoubtsImport } from './routes/event.$id.doubts'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LayoutaRoute = LayoutaImport.update({
  id: '/_layouta',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const EventIdRoute = EventIdImport.update({
  path: '/event/$id',
  getParentRoute: () => rootRoute,
} as any)

const LayoutaTasksRoute = LayoutaTasksImport.update({
  path: '/tasks',
  getParentRoute: () => LayoutaRoute,
} as any)

const EventIdNotesRoute = EventIdNotesImport.update({
  path: '/notes',
  getParentRoute: () => EventIdRoute,
} as any)

const EventIdNextStepsRoute = EventIdNextStepsImport.update({
  path: '/next-steps',
  getParentRoute: () => EventIdRoute,
} as any)

const EventIdDoubtsRoute = EventIdDoubtsImport.update({
  path: '/doubts',
  getParentRoute: () => EventIdRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layouta': {
      preLoaderRoute: typeof LayoutaImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_layouta/tasks': {
      preLoaderRoute: typeof LayoutaTasksImport
      parentRoute: typeof LayoutaImport
    }
    '/event/$id': {
      preLoaderRoute: typeof EventIdImport
      parentRoute: typeof rootRoute
    }
    '/_layout/': {
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/event/$id/doubts': {
      preLoaderRoute: typeof EventIdDoubtsImport
      parentRoute: typeof EventIdImport
    }
    '/event/$id/next-steps': {
      preLoaderRoute: typeof EventIdNextStepsImport
      parentRoute: typeof EventIdImport
    }
    '/event/$id/notes': {
      preLoaderRoute: typeof EventIdNotesImport
      parentRoute: typeof EventIdImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutRoute.addChildren([LayoutIndexRoute]),
  LayoutaRoute.addChildren([LayoutaTasksRoute]),
  LoginRoute,
  EventIdRoute.addChildren([
    EventIdDoubtsRoute,
    EventIdNextStepsRoute,
    EventIdNotesRoute,
  ]),
])

/* prettier-ignore-end */
